version: '3.1'

services:

  wordpress:
    image: kuborgh/php-5.2
    ports:
      - 8888:80
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - ./wp:/project
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"

volumes:
  wordpress:
